/**
 * "Golden Starter" templates give the Coder Agent a safe baseline for common
 * project configurations so it doesn't have to reinvent boilerplate every run.
 *
 * Each template is a map of `filePath → fileContent`.
 * The File Orchestrator injects these at the start of a session before calling
 * the Coder Agent for domain-specific files.
 */

export type StarterTemplate = Record<string, string>;

// ---------------------------------------------------------------------------
// Next.js 15 (TypeScript, App Router, Tailwind CSS)
// ---------------------------------------------------------------------------

export const nextjsStarterTemplate: StarterTemplate = {
  "package.json": JSON.stringify(
    {
      name: "web",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "15.3.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
      devDependencies: {
        "@types/node": "^22.0.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        typescript: "5.9.2",
        tailwindcss: "^3.4.0",
        autoprefixer: "^10.4.0",
        postcss: "^8.4.0",
        eslint: "^9.0.0",
        "eslint-config-next": "15.3.0",
      },
    },
    null,
    2,
  ),

  "tsconfig.json": JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  ),

  "tailwind.config.ts": `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`,

  "postcss.config.mjs": `/** @type {import('postcss').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
`,

  "next.config.ts": `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`,

  "src/app/layout.tsx": `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by Nagini",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,

  "src/app/globals.css": `@tailwind base;
@tailwind components;
@tailwind utilities;
`,

  "src/app/page.tsx": `export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-3xl font-bold">Hello, World!</h1>
    </main>
  );
}
`,
};

// ---------------------------------------------------------------------------
// Java Spring Boot 3 (Maven, Java 21, JPA, PostgreSQL)
// ---------------------------------------------------------------------------

export const javaStarterTemplate: StarterTemplate = {
  "pom.xml": `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.4.0</version>
    <relativePath/>
  </parent>

  <groupId>com.example</groupId>
  <artifactId>app</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>app</name>
  <description>Generated by Nagini</description>

  <properties>
    <java.version>21</java.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
`,

  "src/main/resources/application.properties": `spring.application.name=app
spring.datasource.url=\${DATABASE_URL:jdbc:postgresql://localhost:5432/app}
spring.datasource.username=\${DB_USER:postgres}
spring.datasource.password=\${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
server.port=\${PORT:8080}
`,

  "src/main/java/com/example/app/AppApplication.java": `package com.example.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AppApplication {
    public static void main(String[] args) {
        SpringApplication.run(AppApplication.class, args);
    }
}
`,
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export type ProjectType = "nextjs" | "java" | "unknown";

/**
 * Detect the project type from a blueprint's tech stack entries.
 */
export function detectProjectType(techStackNames: string[]): ProjectType {
  const names = techStackNames.map((n) => n.toLowerCase());
  if (names.some((n) => n.includes("next") || n.includes("react"))) {
    return "nextjs";
  }
  if (
    names.some(
      (n) => n.includes("spring") || n.includes("java") || n.includes("maven"),
    )
  ) {
    return "java";
  }
  return "unknown";
}

/**
 * Returns the starter template for the given project type.
 * Returns an empty record for unknown project types.
 */
export function getStarterTemplate(type: ProjectType): StarterTemplate {
  if (type === "nextjs") return nextjsStarterTemplate;
  if (type === "java") return javaStarterTemplate;
  return {};
}
